> SCAPS 3.3.03 ELIS-UGent: Version scaps3303.exe, dated 14-07-2016, 10:10:12
> SCAPS Scale settings file, saved on 	06-01-2019 at 13:39:01
> problem definition file loaded :
> d:\Samples\DeepL\FeB\Scaps3302\def\SC_NoDefect_NoLight.scaps
> last saved: 	06-01-2019 at 12:49:02
> 

xaxis mode : 1 
xaxis minimum :    2.9800e+02 
xaxis maximum :    3.0050e+02 
yaxis mode : 0 
yaxis minimum :    0.0000e+00 
yaxis maximum :    1.0000e+00 
