> SCAPS 3.3.03 ELIS-UGent: Version scaps3303.exe, dated 17-02-2016, 11:00:14
> SCAPS Scale settings file, saved on 	21-11-2016 at 17:40:40
> problem definition file loaded :
> c:\Диплом Полупроводниковые панели\Установка\def\1set.scaps
> last saved: 	21-11-2016 at 17:39:13
> 

xaxis mode : 1 
xaxis minimum :    2.9700e+02 
xaxis maximum :    3.0050e+02 
yaxis mode : 0 
yaxis minimum :    0.0000e+00 
yaxis maximum :    1.0000e+00 
